server:
  port: 80
#  ssl:
#    key-store: classpath:5947600_chenetchen.ltd.pfx
#    key-store-password: 6mcKnQ6f

spring:
  application:
    name: ChenetBlog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&serverTimezone=UTC
    username: root
    password: chenaichenet
  thymeleaf:
    mode: HTML
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.yeah.net
    username: chenaichenet@yeah.net
    password: QNBVBXLJCBFGQPTV
    protocol: SMTP
    templatePath: templates/mailTemplate.html
  redis:
    host: 127.0.0.1
    password: chenaichenet
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 50 #连接池最大连接数（使用负值表示没有限制）
        max-wait: 3000 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 20   #连接池中的最大空闲连接
        min-idle: 2    #连接池中的最小空闲连接
    timeout: 5000      #连接超时时间（毫秒）
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

uploadFile:
  linux-path: /project/ChenetBlog/src/main/resources/static/upload/images/   #Linux下上传文件所在路径
  windows-path: \\src\\main\\resources\\static\\upload\\images\\   #Windows下上传文件所在路径

logging:
  level:
    root: info
    com.chen.website: warn
  file:
    name: logs/website-dev.log