server:
  port: 9001
  httpPort: 80
  portStatus: true #true表示80和443都能使用，false表示80转发到443
  ssl:
    enabled: true
    key-store: classpath:chenetchen.ltd.pfx
    key-store-password: 6mcKnQ6f
    key-store-type: PKCS12
  servlet:
    session:
      tracking-modes: cookie

spring:
  application:
    name: ChenetWebsite
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/website?useUnicode=true&serverTimezone=UTC
    username: root
    password: 123456
  thymeleaf:
    mode: HTML
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    #show-sql: true
  mail:
    host: smtp.163.com
    username: chenaichenet@163.com
    password: LTXPVFLJINODVNEL
    protocol: SMTP
    templatePath: templates/mailTemplate.html
  redis:
    host: 127.0.0.1
    #password: chenaichenet
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 50 #连接池最大连接数（使用负值表示没有限制）
        max-wait: 3000 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 20   #连接池中的最大空闲连接
        min-idle: 2    #连接池中的最小空闲连接
    timeout: 5000      #连接超时时间（毫秒）
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  messages:
    basename: i18n/message
    encoding: UTF-8

uploadFile:
  images:
    linux-path: /root/project/ChenetWebsite/src/main/resources/static/upload/blogPictures/   #Linux下上传文件所在路径
    windows-path: \\src\\main\\resources\\static\\upload\\blogPictures\\   #Windows下上传文件所在路径

ipFilter:
  limited-time: 600000 #默认限制时间（毫秒）
  safe-time: 5000      #最小安全时间
  limit-number: 50      #限制访问次数

logging:
  level:
    root: info
    com.chen.website: warn
  file:
    name: logs/website-dev.log